csvs:
  guardar_copia_no_cifrada: True
  fecha_inicio_empresa: 2020/01/01
  fecha_cierre: 2025/06/01
  clientes: 
    total_clientes: 200
    fraccion_clientes_empresas: 0.5
    primer_rut_cliente: 5000000
    ultimo_rut_cliente: 23000000
    expectativa_pago_general: [1.8, 0.5, 0.3]
    expectativa_tiempo_general: [2.5, 0.5, 0.3]
  proyectos:
    frecuencias: {"1":0.50, "2":0.17, "3":0.10, "4":0.07, "5":0.05, "6":0.04, "7":0.03, "8":0.02, "9":0.01, "10":0.01}
    maximo_proyectos_por_tipo: 5
    fraccion_cotiz_recotiz_ot: [0.80, 0.08, 0.40]
  precios:
    uf_por_año: {"2025":38419, "2024":36798, "2023":35122,"2022":30997,"2021":29069,"2020":28311}
    tasa_overhead: 0.4
    margen_ganancia: 0.0
    precio_uf_dia_estacionamiento_liviana: 1
    precio_uf_dia_estacionamiento_pesada: 3
  trabajadores:
    fraccion_de_hh_en_sueldo: 0.2

instancias:
  semilla: 2
  solo_trabajadores_fijos: True
  clientes:
    xpeak_llegada_clientes: 0.2
    ypeak_llegada_clientes: 0.6
    yfinal_llegada_clientes: 0.5
    probabilidad_perdida_por_rechazo: 0.2
  proyectos:
    ancho_dist_maquinas_personas: 0.5
    ancho_dist_maquinas_empresas: 8.0
    probabilidad_periodicidad_personas: 0.25
    probabilidad_periodicidad_empresas: 0.70
  estacionamientos: {"maquinaria liviana": 3, "maquinaria pesada":5}
  servicios:
    multiplicador_tiempo_planificacion: 2
    max_intentos_compra: 30
    maximo_factor_demora_cr_a_ideal: 1.3


