name: Verificación básica

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script base
      run: |
        python scripts/db01_crea_base_de_datos.py

