name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_ADMIN_USER: postgres
      DB_ADMIN_PASSWORD: postgres
      DB_ADMIN_DB: postgres
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb
      DB_HOST: localhost
      DB_PORT: 5432
      PGPASSWORD: postgres


    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PostgreSQL client
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run app scripts
      run: |
        python scripts/db01_crea_base_de_datos.py
        python scripts/db02_crea_tablas.py

